"""
Deprecated: JSON-to-Markdown converter.

The test reporting flow now writes Markdown directly during pytest_sessionfinish.
This module is retained for backward compatibility but is no longer used.
"""

from typing import List


def convert_test_logs_to_markdown(*args, **kwargs) -> List[str]:
    """Deprecated shim: direct Markdown is generated by the new TestLogger.

    Returns an empty list to indicate no post-conversion is required.
    """
    return []