version: '3.8'

services:
  # Frontend - React application built with Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: runner-pilot-frontend
    restart: unless-stopped
    networks:
      - runner-pilot-network
    ports:
      - "4173:4173"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  runner-pilot-network:
    driver: bridge
