version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-service-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    networks:
      - app-network
    command: >
      bash -c "bash /app/scripts/prestart.sh &&
               fastapi run --workers 1 --reload app/main.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
