services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8085:80"
    env_file:
      - dev.env
    volumes:
      - ~/.volumn/dev_service/pgadmin:/var/lib/pgadmin
