
services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    env_file:
      - dev.env
    volumes:
      - ~/.volumn/dev_service/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

